name: Post Push Checks

on:
  push:
    branches-ignore:
      - 'production'
      - 'staging'
    paths:
      - '**/*.tsx'
      - '**/*.ts'
      - '**/*.json'
      - '**/*.yaml'
      - '.github/workflows/check-project.yml'
      - '.eslintrc.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set sha7 env variable
        run: echo "SHA7=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Use Node.js v14.15.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.1'
          cache: 'npm'

      - name: Install project
        run: npm install
        working-directory: .

      - name: Run linter
        run: npm run lint
        working-directory: .

      - name: Run build
        run: npm run build
        working-directory: .
